config/routes.rb
Rails.application.routes.draw do
  get 'main/logout'
  get 'main/login'

  get 'main/index'

  devise_for :users

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

  root to: 'main#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to login_path, :notice => 'You are not logged in.'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
 # before_action :authenticate_user!, :except => [:show, :index]

  #  http://stackoverflow.com/questions/23555618/redirect-to-log-in-page-if-user-is-not-authenticated-with-devise
  before_filter :authenticate_user!, :only => [:show, :index]

  ## if you want specific action for require authentication
  ## before_filter :authenticate_user!, :only => [:action1, :action2]

  def login

  end

  def logout

  end

  def index
    unless user_signed_in?
           redirect_to(main_logout_url)
 #         redirect("layouts/user_widget")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def last_visit
    if cookies[:the_time]
      diff = (Time.now.to_i - cookies[:the_time].to_i)  # calc seconds since last visit
      diff = diff/(24*60*60)                            # convert to days
      tmp = Time.at(cookies[:the_time].to_i).strftime("%B %e, %Y at %I:%M %p")
      if diff < 120
        render(:text => "The last time you visited was #{tmp}")
      else
        render(:text => "Your last visit was too long ago #{tmp}" )
      end
    else
      #render(:text => "Welcome!" )
    end
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_user_widget.erb
<% if user_signed_in? %>
    <p>Welcome <%= current_user.email %></p>
    <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
    <p>You are not signed in.</p>
    <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacepageAuthTest</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- START_HIGHLIGHT -->
<body class='<%= controller.controller_name %>'>
<!-- END_HIGHLIGHT -->
<div id="banner">
  <%= image_tag("logo.png", size: "105") %>
  <%= @page_title || "Facepage" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div id="greeting">
  <% if user_signed_in? %>
      <p> Welcome <%= current_user.email %>&nbsp;&nbsp;<%= last_visit %></p>
  <% else %>
      <p>You are not signed in.</p>
  <% end %>
</div>
<div id="columns">
  <div id="side">
    <ul>
      <li><a href="<%=main_index_url%>">Home</a></li>
      <li><a href="http://www..../profile">Profile</a></li>
      <li><a href="http://www..../friends">Friends</a></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
    </ul>
  </div>
  <div id="main">
    <%= yield %>
    <%#= render 'layouts/user_widget' %>
  </div>
</div>
</body>
<%cookies[:the_time] = Time.now.to_i%>
<%#cookies[:the_time] = 125.days.ago.to_i%>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/login.html.erb
<%#= render 'layouts/user_widget' %>
<% if user_signed_in? %>
    <p>Welcome <%= current_user.email %></p>
    <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
    <p>You are not signed in.</p>
    <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/main/logout.html.erb
<h1>Main#logout</h1>
<p>Find me in app/views/main/logout.html.erb</p>